export const TASKFLOW_TOOL_KEYS = [
  "listTasks",
  "getTask",
  "createTask",
  "updateTask",
  "deleteTask",
  "listNotes",
  "getNote",
  "createNote",
  "updateNote",
  "deleteNote",
  "listProjects",
  "getProject",
  "createProject",
  "updateProject",
  "deleteProject",
  "listInboxItems",
  "getInboxItem",
  "createInboxItem",
  "updateInboxItem",
  "deleteInboxItem",
] as const;
