// Mock data for Phase 1 UI testing
export const mockTasks = [
  {
    _id: "task-1",
    title: "Write project specification",
    description:
      "Define scope, requirements, and deliverables for Q1 initiative",
    status: "Not Started",
    priority: "high",
    dueDate: null,
    scheduledDate: null,
    completionDate: null,
    projectId: "proj-1",
    tagIds: ["tag-1", "tag-2"],
    parentTaskId: null,
    estimatedDuration: 120,
    actualDuration: null,
    energyLevel: "high",
    context: ["@office"],
    source: "created",
    orderIndex: 0,
    lastActiveAt: Date.now() - 86400000,
    streakCount: 0,
    difficulty: "medium",
    isTemplate: false,
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 86400000,
  },
  {
    _id: "task-2",
    title: "Review pull requests",
    description: "Code review for authentication feature",
    status: "To Do",
    priority: "medium",
    dueDate: Date.now() + 86400000,
    scheduledDate: "2026-02-01",
    completionDate: null,
    projectId: "proj-2",
    tagIds: ["tag-3"],
    parentTaskId: null,
    estimatedDuration: 60,
    actualDuration: null,
    energyLevel: "medium",
    context: ["@office", "@calls"],
    source: "inbox",
    orderIndex: 0,
    lastActiveAt: Date.now(),
    streakCount: 3,
    difficulty: "easy",
    isTemplate: false,
    createdAt: Date.now() - 43200000,
    updatedAt: Date.now(),
  },
  {
    _id: "task-3",
    title: "Fix authentication bug",
    description: "Users unable to login with OAuth providers",
    status: "In Progress",
    priority: "high",
    dueDate: Date.now() + 172800000,
    scheduledDate: "2026-02-01",
    completionDate: null,
    projectId: "proj-2",
    tagIds: ["tag-3", "tag-4"],
    parentTaskId: null,
    estimatedDuration: 180,
    actualDuration: 90,
    energyLevel: "high",
    context: ["@home"],
    source: "created",
    orderIndex: 0,
    lastActiveAt: Date.now() - 3600000,
    streakCount: 1,
    difficulty: "hard",
    isTemplate: false,
    createdAt: Date.now() - 604800000,
    updatedAt: Date.now() - 3600000,
  },
  {
    _id: "task-4",
    title: "Send client invoice",
    description: "Monthly billing for consulting services",
    status: "To Do",
    priority: "low",
    dueDate: Date.now() + 259200000,
    scheduledDate: null,
    completionDate: null,
    projectId: "proj-3",
    tagIds: ["tag-5"],
    parentTaskId: null,
    estimatedDuration: 30,
    actualDuration: null,
    energyLevel: "low",
    context: ["@office"],
    source: "created",
    orderIndex: 1,
    lastActiveAt: Date.now() - 172800000,
    streakCount: 0,
    difficulty: "easy",
    isTemplate: false,
    createdAt: Date.now() - 345600000,
    updatedAt: Date.now() - 172800000,
  },
  {
    _id: "task-5",
    title: "Deploy version 1.0",
    description: "Production deployment and release notes",
    status: "Completed",
    priority: "high",
    dueDate: Date.now() - 86400000,
    scheduledDate: "2026-01-30",
    completionDate: Date.now() - 43200000,
    projectId: "proj-1",
    tagIds: ["tag-1"],
    parentTaskId: null,
    estimatedDuration: 120,
    actualDuration: 150,
    energyLevel: "high",
    context: ["@office"],
    source: "created",
    orderIndex: 0,
    lastActiveAt: Date.now() - 43200000,
    streakCount: 2,
    difficulty: "hard",
    isTemplate: false,
    createdAt: Date.now() - 1209600000,
    updatedAt: Date.now() - 43200000,
  },
  {
    _id: "task-6",
    title: "Update documentation",
    description: "API docs and user guides for new features",
    status: "Not Started",
    priority: "medium",
    dueDate: null,
    scheduledDate: null,
    completionDate: null,
    projectId: "proj-1",
    tagIds: ["tag-2"],
    parentTaskId: null,
    estimatedDuration: 240,
    actualDuration: null,
    energyLevel: "medium",
    context: ["@home"],
    source: "ai-suggested",
    orderIndex: 1,
    lastActiveAt: Date.now() - 259200000,
    streakCount: 0,
    difficulty: "medium",
    isTemplate: false,
    createdAt: Date.now() - 604800000,
    updatedAt: Date.now() - 259200000,
  },
  {
    _id: "task-7",
    title: "Weekly team standup",
    description: "Sync on progress and blockers",
    status: "To Do",
    priority: "medium",
    dueDate: Date.now() + 86400000,
    scheduledDate: "2026-02-01",
    completionDate: null,
    projectId: null,
    tagIds: ["tag-6"],
    parentTaskId: null,
    estimatedDuration: 30,
    actualDuration: null,
    energyLevel: "medium",
    context: ["@office"],
    source: "created",
    orderIndex: 2,
    lastActiveAt: Date.now() - 604800000,
    streakCount: 5,
    difficulty: "easy",
    isTemplate: false,
    createdAt: Date.now() - 1209600000,
    updatedAt: Date.now() - 604800000,
  },
  {
    _id: "task-8",
    title: "Research new database options",
    description: "Evaluate PostgreSQL vs. other solutions for scaling",
    status: "In Progress",
    priority: "low",
    dueDate: Date.now() + 604800000,
    scheduledDate: null,
    completionDate: null,
    projectId: "proj-2",
    tagIds: ["tag-3", "tag-7"],
    parentTaskId: null,
    estimatedDuration: 480,
    actualDuration: 120,
    energyLevel: "medium",
    context: ["@home"],
    source: "inbox",
    orderIndex: 1,
    lastActiveAt: Date.now() - 86400000,
    streakCount: 0,
    difficulty: "medium",
    isTemplate: false,
    createdAt: Date.now() - 2419200000,
    updatedAt: Date.now() - 86400000,
  },
];

// Mock projects for reference
export const mockProjects = {
  "proj-1": { name: "Product Launch", color: "#3b82f6" },
  "proj-2": { name: "Platform Migration", color: "#10b981" },
  "proj-3": { name: "Client Work", color: "#f59e0b" },
};

// Mock tags for reference
export const mockTags = {
  "tag-1": { name: "urgent", color: "#ef4444" },
  "tag-2": { name: "documentation", color: "#8b5cf6" },
  "tag-3": { name: "backend", color: "#3b82f6" },
  "tag-4": { name: "bug", color: "#ef4444" },
  "tag-5": { name: "billing", color: "#10b981" },
  "tag-6": { name: "meeting", color: "#f59e0b" },
  "tag-7": { name: "research", color: "#6366f1" },
};

export type Task = (typeof mockTasks)[0];
